apiVersion: apps/v1
kind: Deployment
metadata:
 name: apache-web
 namespace: default
 labels:
  app: apache-web
spec:
 replicas: 2
 selector:
  matchLabels:
   app: apache-web
 template:
  metadata:
   labels:
    app: apache-web
  spec:
   containers:
   - name: apache-web
     image: apache-web:latest
     imagePullPolicy: Never
     ports:
     - containerPort: 80
